
export const mockInvitations = [
  {
    id: 1,
    company_name: "HK KANDIVAN INTERNATIONAL TRADING COMPANY LIMITED",
    contact_name: "KHALIL HISHAM ABDALLAH SHWAIKI",
    phone: "008613332800284",
    ione_code: "IONE008613332800284",
    address: "H A192/193, Shenzhen Huaqiang North Manah A Building, manha, Shenzhen city, Dongguan province, China 🇨🇳",
    category: "Trucks spare parts",
    note: "This broker can see the updated categories when integrated with the seller and buyer",
    status: "Pending",
    role: "broker",
  },
  {
    id: 2,
    company_name: "XINLONG AUTO EXPORTS CO. LTD",
    contact_name: "WANG LEI",
    phone: "008613355509909",
    ione_code: "IONE008613355509909",
    address: "Room 308, Tower C, Guangzhou Business Center, Guangzhou City, China",
    category: "Engine Parts",
    note: "Pending approval from buyer",
    status: "Pending",
    role: "broker",
  },
  {
    id: 3,
    company_name: "MEGA PARTS INTL",
    contact_name: "HUSSEIN AL AMEERI",
    phone: "00971556677883",
    ione_code: "IONE00971556677883",
    address: "Office 23, Auto Market, Sharjah, UAE",
    category: "Body Parts",
    note: "Integrated with 2 sellers already",
    status: "Accepted",
    role: "broker",
  },
];
